unclean_department <- c('girls wear, 4-6x  and 7-14', 'health and beauty aids', 'ladieswear', 'menswear', 'optical - frames', 'optical - lenses', 'pharmacy otc', 'pharmacy rx')
clean_department <- c('ladies wear', 'health & beauty', 'ladies wear', 'mens wear', 'optical', 'optical', 'pharmacy', 'pharmacy')
department_unique <- c('1-hr photo',
                       'accessories',
                       'automotive',
                       'bakery',
                       'bath and shower',
                       'beauty',
                       'bedding',
                       'books and magazines',
                       'boys wear',
                       'bras & shapewear',
                       'cameras and supplies',
                       'candy, tobacco, cookies',
                       'celebration',
                       'comm bread',
                       'concept stores',
                       'cook and dine',
                       'dairy',
                       'dsd grocery',
                       'electronics',
                       'fabrics and crafts',
                       'financial services',
                       'frozen foods',
                       'furniture',
                       'ladies wear',
                       'grocery dry goods',
                       'hardware',
                       'health & beauty',
                       'home decor',
                       'home management',
                       'horticulture and access',
                       'household chemicals/supp',
                       'household paper goods',
                       'impulse merchandise',
                       'infant apparel',
                       'infant consumable hardlines',
                       'jewelry and sunglasses',
                       'ladies socks',
                       'ladies wear',
                       'large household goods',
                       'lawn and garden',
                       'liquor,wine,beer',
                       'meat - fresh & frozen',
                       'media and gaming',
                       'mens wear',
                       'mens wear',
                       'office supplies',
                       'optical',
                       'optical',
                       'other departments',
                       'paint and accessories',
                       'personal care',
                       'pets and supplies',
                       'pharmacy',
                       'pharmacy',
                       'players and electronics',
                       'plus and maternity',
                       'pre packed deli',
                       'produce',
                       'seafood',
                       'seasonal',
                       'service deli',
                       'sheer hosiery',
                       'shoes',
                       'sleepwear/foundations',
                       'sporting goods',
                       'swimwear/outerwear',
                       'toys',
                       'wireless')
groups_department <- c('other departments',
                       'accessories',
                       'electronics',
                       'food',
                       'health & beauty',
                       'health & beauty',
                       'cloth',
                       'media and gaming',
                       'cloth',
                       'cloth',
                       'electronics',
                       'food',
                       'other departments',
                       'food',
                       'other departments',
                       'food',
                       'food',
                       'food',
                       'electronics',
                       'other departments',
                       'other departments',
                       'food',
                       'house',
                       'cloth',
                       'food',
                       'electronics',
                       'health & beauty',
                       'home',
                       'home',
                       'garden',
                       'house',
                       'house',
                       'other departments',
                       'infant',
                       'infant',
                       'accessories',
                       'cloth',
                       'cloth',
                       'house',
                       'garden',
                       'food',
                       'food',
                       'media and gaming',
                       'cloth',
                       'cloth',
                       'office',
                       'cloth',
                       'cloth',
                       'other departments',
                       'house',
                       'health & beauty',
                       'other departments',
                       'health & beauty',
                       'health & beauty',
                       'games',
                       'health & beauty',
                       'food',
                       'food',
                       'food',
                       'food',
                       'food',
                       'cloth',
                       'cloth',
                       'cloth',
                       'cloth',
                       'cloth',
                       'infant',
                       'electronics')